### ISSUE TITLE
Weapon dropping/picking

### ISSUE THREAD

**Issue by SuperCHAOSXXX** [yapb/yapb#523] opened 2024-02-11 00:53 UTC
I tried the latest build 4.4.957, when bots started buying their weapons, after that they started dropping their secondary weapon and then picking it, repeating it again and again, like in a loop, and then there were some weird weapon picking sounds at the round start area, i really don't know why those sounds were happening. So far i didn't come across on any serious issues. If i see something else, i'll gladly report.

**Comment by jeefo** [comment] 2024-02-13 08:28
Can't reproduce locally. Mods?

**Comment by di57inct** [comment] 2024-02-15 14:22
Confirming issue. Demo here: https://hotfil.es/1689258
Neccessary resources can be downloaded from server 82.76.20.181:27015

**Comment by SuperCHAOSXXX** [comment] 2024-02-16 12:43
> Can't reproduce locally. Mods?

I have War3FT and CSDM, and i have "Item mode" disabled on CSDM, and this issue happens only when this option is enabled

//
// Allows bots pickup mod items like ammo, health kits and suits.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_pickup_ammo_and_kits "1"

When i turned it to "0", the bots behaved correctly. But is it normal for the bots to behave like this, even when such mods aren't installed? I don't know if it's gonna be the same issue with "yb_attack_monsters" and "yb_pickup_custom_items" when such mods are installed, it'll need testing probably.

**Comment by jeefo** [comment] 2024-02-16 19:01
Should be fixed in latest build.

**Comment by SuperCHAOSXXX** [comment] 2024-02-16 23:21
> Should be fixed in latest build. Please test.

Tested and it's fixed, works like a gem.

**Comment by di57inct** [comment] 2024-02-16 23:30
+++ also confirming full fix including for picking up custom items. Great job 💪

**Comment by SuperCHAOSXXX** [comment] 2024-02-17 02:16
> +++ also confirming full fix including for picking up custom items. Great job 💪

Thanks, just doing whatever i can to help make YaPB better, nothing special.

**Closed** 2024-02-17 19:36 UTC
