### ISSUE TITLE
Latest version (4.1.563) may crash server

### ISSUE THREAD

**Issue by yuusuke09** [yapb/yapb#199] opened 2020-11-13 05:07 UTC
Hi, I tried the latest version, and it always made my server crashed. After I change back to 4.1.551, it hasn't crashed.

Crashed map→ de_nuke_2006 + 30 bots
Metamod-p 1.21v39 APG
AMXX 1.10.1 APG

**Comment by Vladislav4KZ** [comment] 2020-11-13 06:06
I confirm, my server is crashing too. Without metamod and amxx

**Comment by jeefo** [comment] 2020-11-13 08:27
Windows i suppose ?

**Comment by yuusuke09** [comment] 2020-11-13 10:20
> 
> 
> Windows i suppose ?

Yes, win10 20h2.

**Comment by jeefo** [comment] 2020-11-13 17:35
For some reason vanilla HLDS and listenserver engine binary isn't working with mingw-compiled binary. Not sure why, haven't had time to investigate deeply. However ReHLDS binary is working just fine.

So to keep latest build working, i have switch build system to use plain old MSVC. As for now, i keep this issue open, as mingw should be fixed.

Latest binaries should be OK.

**Comment by yuusuke09** [comment] 2020-11-14 05:07
> 
> 
> For some reason vanilla HLDS and listenserver engine binary isn't working with mingw-compiled bot binary. Not sure why, haven't had time to investigate deeply. However ReHLDS binary is working just fine.
> 
> So to keep latest build working, i have switch build system to use plain old MSVC. As for now, i keep this issue open, as mingw should be fixed.
> 
> Latest binaries should be OK.

Just tested with the latest HLDS 8684. Ver.556 works good. Thanks.

**Comment by jeefo** [comment] 2020-11-14 16:23
[yapb.zip](https://github.com/yapb/yapb/files/5541081/yapb.zip) can you verify if this mingw build works for u ?

**Comment by yuusuke09** [comment] 2020-11-15 16:12
> 
> 
> [yapb.zip](https://github.com/yapb/yapb/files/5541081/yapb.zip) can you verify if this mingw build works for u ?

I tried this dll, but it still made my server crashed.

**Comment by bringmefans1** [comment] 2021-06-13 09:02
Hallo guys, my server crashes to when the map is changing with both 4.1.551 and with the last version. Server is hosted on linux and i'm using metamod p 1.21, and amxx 1.10.1, rehlds last version

**Comment by Vladislav4KZ** [comment] 2022-01-17 13:02
Is it still relevant? Why is it still hanging in issues?

**Comment by jeefo** [comment] 2022-01-17 14:08
i can't reproduce the crash with hlds @bringmefans1  provided.

**Comment by jeefo** [comment] 2022-01-17 14:09
mingw builds currently not provided, so probably obsolete.

**Closed by jeefo** 2022-01-17 14:09 UTC
Labels: bug
