### ISSUE TITLE
"yb fill" couldn't fill bot with specified personality in console

### ISSUE THREAD

**Issue by yuusuke09** [yapb/yapb#260] opened 2021-11-22 01:52 UTC
I set "yb_quota_mode is fill" and "yb_quota is 0" in config, and use "yb fill 0 5 0 2" in console.
Then it creates 6 bots with random personalities after my server reboots or changes level.

HLDS 8684 + Metamod 1.21.1am + AMXX 1.9.5293 + YaPB 4.2.623

 YaPB Documentation:
 yb fill [team][count][difficulty][personality]

**Comment by jeefo** [comment] 2021-12-06 21:06
how do you check personalities? ``yb list``?

**Comment by yuusuke09** [comment] 2021-12-07 12:41
> 

yes, yb list

**Comment by Vladislav4KZ** [comment] 2023-01-25 08:25
@yuusuke09 this is a mistake in the documentation, for the rusher personality, you need to write the number 1.

For example ``yb fill 0 5 0 1``

0 - normal
1 - rusher
2 - careful
empty - random

It works for me this way, I just checked.

**Comment by Vladislav4KZ** [comment] 2023-01-25 15:52
> yes, yb list.
> It shows bot personalities like "Rusher", "Careful" ,or "normal".

I remember that I also encountered this bug before, but now it doesn't reproduce on the latest build of YaPB with GitHub Actions.

I also checked it through the console command ``yb list``

**Comment by Vladislav4KZ** [comment] 2023-02-08 11:50
Closing, as no longer reproduced

**Closed by Vladislav4KZ** 2023-02-08 11:50 UTC
Labels: bug
