### ISSUE TITLE
Server crashes sometimes when multiple bots join

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#524] opened 2024-02-14 17:26 UTC
```
L 02/14/2024 - 19:06:14: [fwTaskCVarRandomBotQuota]
Hour: 19. Min: 1. Max: 3.
Random: 3. Initial: 3. Final: 6.
Dropped mocanuvladut37 from server
Reason:  Client sent 'drop'
82.76.92.39:27005:reconnect
Dropped sysrq. from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Dropped R2. from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Dropped NoA.XeqTr from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Dropped ƸӜƷ Mara from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Connecting Bot...
Connecting Bot...
Connecting Bot...
Connecting Bot...
/entrypoint.sh: line 73:    21 Segmentation fault      (core dumped) ./hlds_run -console -heapsize 2621440 -norestart -insecure -pingboost 2 -strictportbind -game ${HLDS_GAME} +ip 0.0.0.0 +port ${SERVER_PORT} +maxplayers 32 +map ${SRCDS_MAP} +exec server.cfg
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
```

**Comment by jeefo** [comment] 2024-02-14 17:33
provide plugins and modules list

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ► D i 5 7 i n c T ♪ [ılıl.lılı.ıllı.lııl] ♫ ***@***.***>
Sent: Wednesday, February 14, 2024 8:26:48 PM
To: yapb/yapb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yapb/yapb] Server crashes sometimes when multiple bots join (Issue #524)


L 02/14/2024 - 19:06:14: [fwTaskCVarRandomBotQuota]
Hour: 19. Min: 1. Max: 3.
Random: 3. Initial: 3. Final: 6.
Dropped mocanuvladut37 from server
Reason:  Client sent 'drop'
82.76.92.39:27005:reconnect
Dropped sysrq. from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Dropped R2. from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Dropped NoA.XeqTr from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Dropped ƸӜƷ Mara from server
Reason:  Kicked :"Kicking bot for rejoining on a team"
Connecting Bot...
Connecting Bot...
Connecting Bot...
Connecting Bot...
/entrypoint.sh: line 73:    21 Segmentation fault      (core dumped) ./hlds_run -console -heapsize 2621440 -norestart -insecure -pingboost 2 -strictportbind -game ${HLDS_GAME} +ip 0.0.0.0 +port ${SERVER_PORT} +maxplayers 32 +map ${SRCDS_MAP} +exec server.cfg
***@***.***~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false

**Comment by di57inct** [comment] 2024-02-14 18:12
> Metamod-r v1.3.0.138, API (5:13)
> Metamod-r build: 11:50:32 Nov 28 2023
> Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/5179c25
> AMX Mod X 1.10.0.5467 (http://www.amxmodx.org)
> Authors:
>         David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
>         Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
>         Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
>         Borja "faluco" Ferrer, Scott "DS" Ehlert
> Compiled: Jan 21 2023 20:27:33
> Built from: https://github.com/alliedmodders/amxmodx/commit/27f451a
> Build ID: 5467:27f451a
> Core mode: JIT+ASM32
> Currently loaded plugins:
>       description      stat pend  file                      vers          src  load  unload
>  [ 1] YaPB             RUN   -    yapb.so                   v4.3.734      ini  Chlvl ANY  
>  [ 2] SafeNameAndChat  RUN   -    SafeNameAndChat.so        v1.1          ini  ANY   ANY  
>  [ 3] Reunion          RUN   -    reunion_mm_i386.so        v0.1.0.137    ini  Start Never
>  [ 4] WHBlocker        RUN   -    whblocker_mm_i386.so      v1.5.697      ini  Chlvl ANY  
>  [ 5] AMX Mod X        RUN   -    amxmodx_mm_i386.so        v1.10.0.5467  ini  Start ANY  
>  [ 6] Engine           RUN   -    engine_amxx_i386.so       v1.10.0.5467  pl5  ANY   ANY  
>  [ 7] FakeMeta         RUN   -    fakemeta_amxx_i386.so     v1.10.0.5467  pl5  ANY   ANY  
>  [ 8] CStrike          RUN   -    cstrike_amxx_i386.so      v1.10.0.5467  pl5  ANY   ANY  
>  [ 9] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so  v1.10.0.5467  pl5  ANY   ANY  
>  [10] CSX              RUN   -    csx_amxx_i386.so          v1.10.0.5467  pl5  ANY   ANY  
>  [11] GeoIP            RUN   -    geoip_amxx_i386.so        v1.10.0.5467  pl5  ANY   ANY  
>  [12] Fun              RUN   -    fun_amxx_i386.so          v1.10.0.5467  pl5  ANY   ANY  
>  [13] MySQL            RUN   -    mysql_amxx_i386.so        v1.10.0.5467  pl5  ANY   ANY  
> 13 plugins, 13 running
> Currently loaded plugins:
>        id  name                    version     author            url                              file         status   
>  [  1] 0   Advanced Bans           0.8.1       Exolent                                            advanced_ba  running  
>  [  2] 1   Admin Base              1.10.0.546  AMXX Dev Team                                      admin.amxx   running  
>  [  3] 2   Admin Commands          1.10.0.546  AMXX Dev Team                                      admincmd.am  running  
>  [  4] 3   Admin Help              1.10.0.546  AMXX Dev Team                                      adminhelp.a  running  
>  [  5] 4   Slots Reservation       1.10.0.546  AMXX Dev Team                                      adminslots.  running  
>  [  6] 5   Multi-Lingual System    1.10.0.546  AMXX Dev Team                                      multilingua  running  
>  [  7] 6   Menus Front-End         1.10.0.546  AMXX Dev Team                                      menufront.a  running  
>  [  8] 7   Commands Menu           1.10.0.546  AMXX Dev Team                                      cmdmenu.amx  running  
>  [  9] 8   Players Menu            1.10.0.546  AMXX Dev Team                                      plmenu_ab_b  running  
>  [ 10] 9   Teleport Menu           1.10.0.546  AMXX Dev Team                                      telemenu.am  running  
>  [ 11] 10  Maps Menu               1.10.0.546  AMXX Dev Team                                      mapsmenu.am  running  
>  [ 12] 11  Plugin Menu             1.10.0.546  AMXX Dev Team                                      pluginmenu.  running  
>  [ 13] 12  Anti Flood              1.10.0.546  AMXX Dev Team                                      antiflood.a  running  
>  [ 14] 13  Admin Votes             1.10.0.546  AMXX Dev Team                                      adminvote.a  running  
>  [ 15] 14  NextMap                 1.10.0.546  AMXX Dev Team                                      nextmap.amx  running  
>  [ 16] 15  Nextmap Chooser         1.10.0.546  AMXX Dev Team                                      mapchooser.  running  
>  [ 17] 16  TimeLeft                1.10.0.546  AMXX Dev Team                                      timeleft.am  running  
>  [ 18] 17  Pause Plugins           1.10.0.546  AMXX Dev Team                                      pausecfg.am  running  
>  [ 19] 18  Stats Configuration     1.10.0.546  AMXX Dev Team                                      statscfg.am  running  
>  [ 20] 19  Restrict Weapons        1.10.0.546  AMXX Dev Team                                      restmenu.am  running  
>  [ 21] 20  StatsX                  1.10.0.546  AMXX Dev Team                                      statsx.amxx  running  
>  [ 22] 21  [SCM] Entity Editor     1.3.0       schmurgel1983                                      scm_entity_  running  
>  [ 23] 22  [CS] Team Semiclip      3.3.1       schmurgel1983                                      cs_team_sem  running  
>  [ 24] 23  [AMXX] Settings API     1.0         MeRcyLeZZ                                          amx_setting  running  
>  [ 25] 24  [CS] Ham Hooks for Bot  1.0         WiLS                                               cs_ham_bots  running  
>  [ 26] 25  [CS] Player Models API  1.2.2       WiLS              unknown                          cs_player_m  running  
>  [ 27] 26  [CS] Weapon Models API  1.1         WiLS                                               cs_weap_mod  running  
>  [ 28] 27  D7 (Dis)connect Messag  1.3.9       D i 5 7 i n c T                                    D7(Dis)conn  running  
>  [ 29] 28  D7 Admin free look      0.0.2       D i 5 7 i n c T                                    D7AdminFree  running  
>  [ 30] 29  D7 Bot Gameplay         0.1.6       D7                unknown                          D7BotGamepl  debug    
>  [ 31] 30  D7 Bot Name             0.0.4       D i 5 7 i n c T                                    D7BotName.a  running  
>  [ 32] 31  D7 Bot Quota            0.0.8       D i 5 7 i n c T   unknown                          D7BotQuota.  running  
>  [ 33] 32  D7 Camera               0.2.3       XunTric, D i 5 7  unknown                          D7Camera.am  running  
>  [ 34] 33  D7 HostName Scroll      0.0.3       D i 5 7 i n c T                                    D7HostNameS  running  
>  [ 35] 34  D7 HUD Info             0.0.6       D i 5 7 i n c T                                    D7HUDInfo.a  running  
>  [ 36] 35  Bomb Spawn HUD          1.2.1       bugsy, hornet, D                                   D7HUDInfoC4  running  
>  [ 37] 36  D7 Kill assist          1.1.6       D i 5 7 i n c T,                                   D7KillAssis  running  
>  [ 38] 37  D7 nick changer         1.2.2       D i 5 7 i n c T                                    D7NameChang  running  
>  [ 39] 38  No Radio Flood          1.1.7       Starsailor, rega                                   D7NoRadioFl  running  
>  [ 40] 39  D7 Parachute            0.0.1       D i 5 7 i n c T                                    D7Parachute  running  
>  [ 41] 40  D7 Player Model Menu    0.3.4       D i 5 7 i n c T   unknown                          D7PlayerMod  running  
>  [ 42] 41  D7 Remember weapon sil  0.0.5       D7                                                 D7RememberW  running  
>  [ 43] 42  D7 Reset Score          1.0.2       D i 5 7 i n c T                                    D7ResetScor  running  
>  [ 44] 43  D7 Reward: Kill         0.0.8       D i 5 7 i n c T                                    D7RewardKil  running  
>  [ 45] 44  D7 Spawn Features       0.0.3       D i 5 7 i n c T                                    D7SpawnFeat  running  
>  [ 46] 45  D7 Spawn Swapper        0.2.7       D7, xPaw                                           D7SpawnSwap  debug    
>  [ 47] 46  D7 Warm & Restart       3.0.8       D i 5 7 i n c T                                    D7WarmResta  running  
>  [ 48] 47  Advanced Mute           2.1         OciXCrom                                           crx_advmute  running  
>  [ 49] 48  OciXCrom's Admin Chat   4.2         OciXCrom                                           crx_adminch  running  
>  [ 50] 49  Best Player MOTD        1.2.2       OciXCrom                                           crx_bestpla  running  
>  [ 51] 50  Style C4 Timer          3.1         OciXCrom                                           crx_c4timer  running  
>  [ 52] 51  CM: Toggle Chat         4.1         OciXCrom                                           crx_chatman  running  
>  [ 53] 52  Command Targeting Plus  1.3         OciXCrom                                           crx_cmdtarg  running  
>  [ 54] 53  Command Restrictions    2.1         OciXCrom                                           crx_command  running  
>  [ 55] 54  Simple Demo Recorder    2.0.3       OciXCrom                                           crx_demorec  running  
>  [ 56] 55  Ultimate Fire in the H  2.1         OciXCrom                                           crx_fireint  running  
>  [ 57] 56  Game Messages & Sounds  3.0.2       OciXCrom                                           crx_gamemes  running  
>  [ 58] 57  GoSpec                  1.2         OciXCrom                                           crx_gospec.  running  
>  [ 59] 58  OciXCrom's Rank System  3.15        OciXCrom                                           crx_ranksys  running  
>  [ 60] 59  Remove Immunity         1.0         OciXCrom                                           crx_remove_  running  
>  [ 61] 60  Let it Snow!            1.0         OciXCrom                                           crx_snow.am  running  
>  [ 62] 61  Spawn Protection        1.1.0       OciXCrom                                           crx_spawn_p  running  
>  [ 63] 62  Autoresponder/Advertis  0.5         MaximusBrood                                       ad_manager.  running  
>  [ 64] 63  Admin Spectator ESP     1.4_beta    KoST                                               admin_spec_  running  
>  [ 65] 64  CS AFK Manager          1.0.6 (amx  Freeman           unknown                          afk_manager  running  
>  [ 66] 65  Auto Join on Connect    0.1         VEN                                                auto_join_o  running  
>  [ 67] 66  Dead Name Change        0.1         VEN                                                dead_name_c  running  
>  [ 68] 67  Flash Remote Control    12.0        OT                                                 flashbang_r  running  
>  [ 69] 68  Invisible Spectator     0.3         ConnorMcLeod                                       invisible_s  paused   
>  [ 70] 69  No See Vars             0.1.0       ConnorMcLeod                                       no_see_vars  running  
>  [ 71] 70  Ping Faker              1.6.4       MeRcyLeZZ                                          pingfaker_m  running  
>  [ 72] 71  PLUGIN                  VERSION     AUTHOR                                             premiumvip.  running  
>  [ 73] 72  Team Balancer           1.8b3       Ptahhotep                                          ptbD7.amxx   running  
>  [ 74] 73  TimeLeft Extender       0.1a        prodigy                                            TimeLeftExt  running  
>  [ 75] 74  Chat Manager            4.8         OciXCrom                                           crx_chatman  running  
> 75 plugins, 74 running

**Comment by jeefo** [comment] 2024-02-14 18:21
please, update bot to 4.4 release in first place

 that's bots-related D7 plugins, isn't seems public, it's will be hard to debug on my side

can you try to run sever with -debug command line switch? or(in worst case) pack addons and send it to ***@***.***? if updating bot version won't help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by di57inct** [comment] 2024-02-14 18:27
Should i update to pre-release or latest release([4.4.957](https://github.com/yapb/yapb/releases/tag/4.4.957))?
Can share bot plugins in private but i really doubt it's their fault as they just kick bots, set them to spectator or change the value of yb_quota.

**Comment by jeefo** [comment] 2024-02-14 18:29
> Should i update to pre-release or latest release([4.4.957](https://github.com/yapb/yapb/releases/tag/4.4.957))? Can share bot plugins in private but i really doubt it's their fault as they just kick bots, set them to spectator or change the value of yb_quota.

4.4 isn't pre-release anymore. so yes, it's correct.

first, try to update bot, if things goes wrong, the  it would be good to take a look at plugins.

**Comment by di57inct** [comment] 2024-02-14 18:34
Forgot to mention the bot gameplay also triggers yb kill automatically.
Updated to [4.4.957](https://github.com/yapb/yapb/releases/tag/4.4.957) and enabled debug and got the following in the console:

> Bogus value for cvar 'yb_difficulty_auto_balance_interval', min is '30.0' and max is '240.0', and we're got '5.0', value reverted to default '30.0'.
> Bogus value for cvar 'yb_quota_adding_interval', min is '0.1' and max is '1.0', and we're got '3.0', value reverted to default '0.1'.

Figured I might as well attach the cfg file in this case too.
```
//
// @package: YaPB
// @version: 4.3
// @author: YaPB Project
// @filename: yapb.cfg
// 
// YaPB main configuration file. Can be executed via "exec" command.
//

//
// Enables or disables useful messages about bot states. Not required for end users.
// ---
// Default: "0", Min: "0", Max: "4"
// 
yb_debug "0"

//
// Forces all alive bots to build path and go to the specified here graph node.
// ---
// Default: "-1", Min: "-1", Max: "2048"
// 
yb_debug_goal "-1"

//
// Specifies the percent of bots, that can follow leader on each round start.
// ---
// Default: "20", Min: "0", Max: "100"
// 
yb_user_follow_percent "20"

//
// Specifies how many bots can follow a single user.
// ---
// Default: "1", Min: "0", Max: "8"
// 
yb_user_max_followers "0"

//
// If enabled, all bots will be forced only the knife, skipping weapon buying routines.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_jasonmode "0"

//
// Allows bots to use radio or chattter.
//  Allowed values: '0', '1', '2'.
//  If '0', radio and chatter is disabled.
//  If '1', only radio allowed.
//  If '2' chatter and radio allowed.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_radio_mode "0"

//
// Specifies whether bots able to use team economics, like do not buy any weapons for whole team to keep money for better guns.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_economics_rounds "1"

//
// Specifies whether bots able to use 'shift' if they thinks that enemy is near.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_walking_allowed "1"

//
// Allows or disallows bots to camp. Doesn't affects bomb/hostage defending tasks.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_camping_allowed "1"

//
// Lower bound of time from which time for camping is calculated
// ---
// Default: "15.0", Min: "5.0", Max: "90.0"
// 
yb_camping_time_min "15.0"

//
// Upper bound of time until which time for camping is calculated
// ---
// Default: "45.0", Min: "15.0", Max: "120.0"
// 
yb_camping_time_max "15.0"

//
// Allows or disallows bots to take revenge of teamkillers / team attacks.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_tkpunish "0"

//
// If enabled, the bots think function is disabled, so bots will not move anywhere from their spawn spots.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_freeze_bots "0"

//
// Allows or disallows the use of spray paints.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_spraypaints "1"

//
// Allows or disallows bots weapon buying routines.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_botbuy "1"

//
// Allows bots to destroy breakables around him, even without touching with them.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_destroy_breakables_around "1"

//
// The radius on which bot searches world for new objects, items, and weapons.
// ---
// Default: "450.0", Min: "64.0", Max: "1024.0"
// 
yb_object_pickup_radius "450.0"

//
// Specifies the paths for the bot chatter sound files.
// ---
// Default: "sound/radio/bot"
// 
yb_chatter_path "sound/radio/bot"

//
// Specifies semicolon separated list of weapons that are not allowed to buy / pickup.
// ---
// Default: ""
// 
yb_restricted_weapons "sgren;shield"

//
// Allows or disallows bots to attack monsters.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_attack_monsters "1"

//
// Allows or disallows bots to pickup custom items.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_pickup_custom_items "1"

//
// Allows or disallows bots to do map objectives, i.e. plant/defuse bombs, and saves hostages.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_objectives "0"

//
// Allows or disallows the ability for random knife attacks when bot is rushing and no enemy is nearby.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_random_knife_attacks "1"

//
// Enables or disables bots chat functionality.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_chat "0"

//
// Bot chances to send random dead chat when killed.
// ---
// Default: "30", Min: "0", Max: "100"
// 
yb_chat_percent "30"

//
// Specifies whether bots able to fire at enemies behind the wall, if they hearing or suspecting them.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_shoots_thru_walls "2"

//
// Enables or disables searching world for enemies.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_enemies "0"

//
// Enables or disables checking enemy rendering flags. Useful for some mods.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_check_enemy_rendering "1"

//
// Enables or disables checking enemy invincibility. Useful for some mods.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_check_enemy_invincibility "1"

//
// Enables or disables bot ability to stab the enemy with knife if bot is in good condition.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_stab_close_enemies "1"

//
// Binds specified key for opening bots menu.
// ---
// Default: "="
// 
yb_bind_menu_key "="

//
// Specifies comma separated list of bot cvars, that will not be overriten by config on changelevel.
// ---
// Default: "yb_quota,yb_autovacate"
// 
yb_ignore_cvars_on_changelevel ""//yb_quota,yb_autovacate

//
// Enables or disables display menu text, when players asks for menu. Useful only for Android.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_display_menu_text "1"

//
// The value (password) for the setinfo key, if user sets correct password, he's gains access to bot commands and menus.
// ---
// Default: ""
// 
yb_password "dsafjhb"

//
// The name of setinfo key used to store password to bot commands and menus.
// ---
// Default: "_ybpw"
// 
yb_password_key "_ybpw"

//
// Enables or disables CSDM / FFA mode for bots.
//  Allowed values: '0', '1', '2', '3'.
//  If '0', CSDM / FFA mode is auto-detected.
//  If '1', CSDM mode is enabled, but FFA is disabled.
//  If '2', CSDM and FFA mode is enabled.
//  If '3', CSDM and FFA mode is disabled.
// ---
// Default: "0", Min: "0", Max: "3"
// 
yb_csdm_mode "0"

//
// Specifies whether bot should not 'fix' camp directions of camp waypoints when loading old PWF format.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_fixcamp "1"

//
// Specifies the URL from bots will be able to download graph in case of missing local one. Set to empty, if no downloads needed.
// ---
// Default: "yapb.jeefo.net"
// 
yb_graph_url "yapb.jeefo.net"

//
// Kick bots to automatically make room for human players.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_autovacate "1"

//
// Specifies the number bots to be added to the game.
// ---
// Default: "9", Min: "0", Max: "32"
// 
yb_quota "5"

yb_quota_adding_interval 3.0

//
// Specifies the type of quota.
//  Allowed values: 'normal', 'fill', and 'match'.
//  If 'fill', the server will adjust bots to keep N players in the game, where N is yb_quota.
//  If 'match', the server will maintain a 1:N ratio of humans to bots, where N is yb_quota_match.
// ---
// Default: "normal"
// 
yb_quota_mode "normal"

//
// Number of players to match if yb_quota_mode set to 'match'
// ---
// Default: "0", Min: "0", Max: "32"
// 
yb_quota_match "0"

//
// Specifies how many times per second bot code will run.
// ---
// Default: "26.0", Min: "24.0", Max: "90.0"
// 
yb_think_fps "26.0"
yb_think_fps_disable 0

//
// Specifies amount of time in seconds when bots will be killed if no humans left alive.
// ---
// Default: "0.0", Min: "0.0", Max: "90.0"
// 
yb_autokill_delay "0.0"

//
// Specifies whether bots should join server, only when at least one human player in game.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_join_after_player "0"

//
// Forces all bots to join team specified here.
// ---
// Default: "any"
// 
yb_join_team "any"

//
// Specifies after how many seconds bots should start to join the game after the changelevel.
// ---
// Default: "5.0", Min: "0.0", Max: "30.0"
// 
yb_join_delay "5.0"

//
// All the bot names will be prefixed with string specified with this cvar.
// ---
// Default: ""
// 
yb_name_prefix ""

//
// All bots difficulty level. Changing at runtime will affect already created bots.
// ---
// Default: "4", Min: "0", Max: "4"
// 
yb_difficulty "1"

//
// Lower bound of random difficulty on bot creation. Only affects newly created bots. -1 means yb_difficulty only used.
// ---
// Default: "-1", Min: "-1", Max: "4"
// 
yb_difficulty_min "-1"

//
// Upper bound of random difficulty on bot creation. Only affects newly created bots. -1 means yb_difficulty only used.
// ---
// Default: "-1", Min: "-1", Max: "4"
// 
yb_difficulty_max "-1"

//
// Enables each bot balances own difficulty based kd-ratio of team.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_difficulty_auto "0"

yb_difficulty_auto_balance_interval 5.0

//
// Enables or disables displaying bot avatars in front of their names in scoreboard. Note, that is currently you can see only avatars of your steam friends.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_show_avatars "1"

//
// Enables latency display in scoreboard.
//  Allowed values: '0', '1', '2'.
//  If '0', there is nothing displayed.
//  If '1', there is a 'BOT' is displayed.
//  If '2' fake ping is displayed.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_show_latency "1"

//
// Allows to save bot names upon changelevel, so bot names will be the same after a map change
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_save_bots_names "1"

//
// Specifies the bots wanted skin for Terrorist team.
// ---
// Default: "0", Min: "0", Max: "5"
// 
yb_botskin_t "0"

//
// Specifies the bots wanted skin for CT team.
// ---
// Default: "0", Min: "0", Max: "5"
// 
yb_botskin_ct "0"

//
// Lower bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "7", Min: "0", Max: "100"
// 
yb_ping_base_min "15"

//
// Upper bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "34", Min: "0", Max: "100"
// 
yb_ping_base_max "25"

//
// Specifies the language for bot messages and menus.
// ---
// Default: "en"
// 
yb_language "en"

//
// Enables or disables extra hard difficulty for bots.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_whose_your_daddy "0"

//
// Selects the heuristic function mode. For debug purposes only.
// ---
// Default: "4", Min: "0", Max: "4"
// 
yb_path_heuristic_mode "4"

//
// Lower bound of danger factor that used to add additional danger to path based on practice.
// ---
// Default: "200", Min: "100", Max: "2400"
// 
yb_path_danger_factor_min "200"

//
// Upper bound of danger factor that used to add additional danger to path based on practice.
// ---
// Default: "400", Min: "200", Max: "4800"
// 
yb_path_danger_factor_max "400"

//
// Enables or disables showing welcome message to host entity on game start.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_display_welcome_text "0"

//
// Enables or disables fake server queries response, that shows bots as real players in server browser.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_enable_query_hook "1"

yb_rotate_bots 1
yb_rotate_stay_max 1800
yb_rotate_stay_min 300
```

**Comment by jeefo** [comment] 2024-02-14 19:13
provide all bots related plugins to yapb@jeefo.net

**Comment by di57inct** [comment] 2024-02-14 20:31
Sent :)

**Comment by di57inct** [comment] 2024-02-14 20:56
Forgot to mention in the email; needed resources can be downloaded by joining server 82.76.20.181:27015

**Comment by jeefo** [comment] 2024-02-14 20:58
![image](https://github.com/yapb/yapb/assets/1781346/40b5dcc7-0983-41d0-a42a-7ea3060d2c0a)

i have already installed, so far no crash :)

**Comment by di57inct** [comment] 2024-02-14 21:26
Have the bots leave and join constantly. Noticed that for some reason since i updated they now rejoin by themselves if set to spectator. How can i stop this behaviour? Also, how can i set the number of bots to have steamid and the number to not have? It seems random to me and rare to happen. Sorry for the offtopic.

**Comment by di57inct** [comment] 2024-02-15 05:42
Figured the best way to replicate this is to have a fixed yb_quota(10 or something like that) and then just to spam kicking them as they would automatically rejoin. Seems like the crash happens when kicked instead of joining, as the moment i kicked a bot via amxx, the chat message didn't print(and the server "kicked" console message didn't either) and the server crashed.

**Comment by jeefo** [comment] 2024-02-15 05:48
Just for test, try to disable Botnames plugin. I still can't reproduce on Debian 12 & Ubuntu 22.04 (WSL)

**Comment by di57inct** [comment] 2024-02-15 06:25
Did it with bot rename plugin disabled.

**Comment by jeefo** [comment] 2024-02-15 21:01
Crash caused by bug in gamedll with combination with tricky bot team management.

@di57inct workaround it on his side.

**Closed by jeefo** 2024-02-15 21:01 UTC
