### ISSUE TITLE
yb_autovacate not working

### ISSUE THREAD

**Issue by redpanama** [yapb/yapb#408] opened 2023-02-14 21:39 UTC
when human player join the match yb_autovacate does not kick bot to make a room. 

**YaPB version 4.3.734**
**Using latest ReHLDS**

Settings used:
yb_autovacate "1"
yb_quota "32"
yb_quota_mode "fill"
yb_quota_match "0"
yb_autokill_delay "1"
yb_join_after_player "0"
yb_join_team "any"
yb_join_delay "5.0"

**metamod plugins:**

linux addons/snac/SafeNameAndChat.so
linux addons/reunion/reunion_mm_i386.so
linux addons/reauthcheck/reauthcheck_mm_i386.so
linux addons/vtc/VoiceTranscoder.so
linux addons/amxmodx/dlls/amxmodx_mm_i386.so
linux addons/whblocker/whblocker_mm_i386.so
linux addons/rechecker/rechecker_mm_i386.so
linux addons/resrdetector/resrdetector_mm_i386.so
linux addons/resemiclip/resemiclip_mm_i386.so
linux addons/yapb/bin/yapb.so

**amxmodx modules:**

fun
engine
fakemeta
geoip
sockets
sockets_hz
regex
nvault
cstrike
csx
hamsandwich
reaimdetector
reapi
orpheu

**Comment by jeefo** [comment] 2023-03-02 11:58
They should be kicked when player joins team. It's standard behaviour.

Due to #415 i hope behaviour should be fixed, to kick bots instantly player joins server.

**Comment by redpanama** [comment] 2023-03-02 12:46
Ok, thanks !

**Comment by Vladislav4KZ** [comment] 2023-03-07 07:55
Doesn't reproduce on original HLDS:
https://github.com/yapb/yapb/issues/415#issuecomment-1457708357

This issue is only related to ReHLDS.

**Comment by jeefo** [comment] 2023-03-13 13:09
Can you check the latest action build ? Controlled via ``cv_kick_after_player_connect`` cvar.

**Closed** 2023-04-04 15:02 UTC
