### ISSUE TITLE
bot ignores config: does headshots although headshotProbability 0

### ISSUE THREAD

**Issue by ghost** [yapb/yapb#359] opened 2022-08-11 17:58 UTC
1. in difficulty cfg i set headshotProbability to 0. but the bots almost always do headshots........... how.
2. it would be good to have 2 delays. 1 delay is the initial aim on enemy visible, and 2 is the delay for shooting, that makes it more human
3. let the bots always face enemy base/line if no enemy visible, they look around like dumb ducks
4. add cfg random margins for aiming like x +-5 and y +-10 
5. cfg to block jump, duck
6. never let the bot walk backwards if no enemy visible
7. on aim_map2 with simple waypoints going in a square across the map, the bots get stuck behind pillars right at spawn and dont get away and just jump at the spot. how??
8. cut the map in half by spawn locations and always make the bot face the front line
9. or make the bot randomly aim at directions of not yet visible enemies, to make them more human its not about where to walk, but where to aim if nobody is visible
10. yb_walking_allowed "0" but bots walk......

**Comment by Vladislav4KZ** [comment] 2022-08-12 08:07
> 10. yb_walking_allowed "0" but bots walk......

This cvar means allowing silent walking and not running. This does not mean that bots will always walk quietly.

``yb_freeze_bots`` means no walking/running at all. The bots will stay put.

**Comment by kaktuspo** [comment] 2022-08-12 11:15
yb_walking_allowed 0  - should disable bot shift walk. but they do shift walk !!!

freeze_bots. yeah thats useless. we need no jump, no duck, and especially no sync jump. i have 3 bots jumping on the spot in sync like its Formation dance olympics

**Comment by Vladislav4KZ** [comment] 2023-02-10 11:00
> yb_walking_allowed 0 - should disable bot shift walk. but they do shift walk !!!

I can't reproduce this bug myself.

If the ``yb_difficulty`` value is equal to ``4``, i.e. "Professional" difficulty level and the ``yb_walking_allowed`` value is equal to ``1``, then bots do "shift walk".

If one of the conditions is not met, then the bots do not "shift walk".

I just checked with myself, when bots use silent walking (like they holding the shift key) I immediately enter the ``yb_walking_allowed 0`` cvar into console, and bots immediately stop using "shift".

Make sure that after typing ``yb_walking_allowed 0`` into the console, you type ``yb cvars save`` to save the changed value of this cvar to yapb.cfg, so that its effect extends to the next map, since the yapb.cfg are reloads after changelevel, and the values ​​of all cvars are restored from that config.

Or you can add that cvar into the ``yb_ignore_cvars_on_changelevel`` so that its value is not overwritten by the one in yapb.cfg

https://yapb.readthedocs.io/en/latest/configuring.html#yb-ignore-cvars-on-changelevel

**Comment by Vladislav4KZ** [comment] 2023-02-10 11:24
> on aim_map2 with simple waypoints going in a square across the map, the bots get stuck behind pillars right at spawn and dont get away and just jump at the spot. how??

Because the graph was made for a different version of the map.

It was made for aim_map2 by Svill (the map author himself made a waypoint for it)
https://www.17buddies.rocks/17b2/View/Map/4332/aim_map2.html

But you apparently use the aim_map2 by Thru$t
https://gamebanana.com/mods/94702

You need to make a new graph for this particular version of the map so that the bots move normally.

**Comment by Vladislav4KZ** [comment] 2023-04-11 10:34
OP's account has been deleted, and this issue also related to https://github.com/yapb/yapb/issues/387

So I'm closing it.

**Closed** 2023-04-11 10:34 UTC
